routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', function () {
    return view('indeks');
});


Route::get('/mutabaah/pdf', 'MutabaahController@pdf')->middleware('auth');
Route::get('/mutabaah/grafik', 'MutabaahController@grafik')->middleware('auth');
Route::resource('mutabaah', 'MutabaahController')->middleware('auth');
Route::get('mutabaah/download/{type}', 'MutabaahController@download')->middleware('isadmin');

Route::resource('prodi', 'ProdiController')->middleware('isadmin');
Route::get('admin', 'DashboardAdminController@dashboard')->middleware('isadmin');
Route::resource('user', 'UserController')->middleware('isadmin');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $primaryKey = 'npm';
    protected $fillable = [
        'name', 'email', 'password', 'npm', 'id_prodi', 'role', 'foto','sex'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Prodi;
use Illuminate\Support\Facades\Hash;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = User::all();

        return view('admin.users.index',compact('users'));         
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $prodis = Prodi::all();
        return view('admin.users.create', compact('prodis'));         
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $file = $request->file('foto');
        $name = 'userbmq' . \Carbon\Carbon::now()->format('YmdHis') . '.' . $file->getClientOriginalExtension();
        $namafoto = $name;
        $foto = $file->storeAs('public/uploads', $name);

        User::create([
            'npm' => $request->get('npm'),
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'password' => Hash::make($request->get('password')),
            'sex' => $request->get('sex'),
            'id_prodi' => $request->get('id_prodi'),
            'role' => $request->get('role'),
            'foto' => $namafoto,
        ]);
        return redirect('user')->with('success','Berhasil Tambah Data');                
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = User::find($id);
        $prodis = Prodi::all();
        return view('admin.users.edit',compact('user','id', 'prodis'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $file = $request->file('foto'); 
        if($file != null){
            $name = 'userbmq' . \Carbon\Carbon::now()->format('YmdHis') . '.' . $file->getClientOriginalExtension();
            $namafoto = $name;
            $foto = $file->storeAs('public/uploads', $name);
        }else{
            $file = User::find($id);            
            $namafoto = $file['foto'];
        }
        $user = User::find($id)
            ->update([
                'npm' => $request->get('npm'),
                'name' => $request->get('name'),
                'email' => $request->get('email'),
                // 'password' => Hash::make($request->get('password')),
                'sex' => $request->get('sex'),
                'id_prodi' => $request->get('id_prodi'),
                'role' => $request->get('role'),
                'foto' => $namafoto,                
            ]);
        return redirect('user')->with('success','Berhasil Tambah Data');        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $user = User::find($id);
        $user->delete();
        return redirect('user')->with('success','User Has Been Deleted');                  
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header bg-green">
                        <h2>
                            User<small>Create Data User</small>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
		                <form method="POST" action="{{ route('user.store') }}" enctype="multipart/form-data">
		                    @csrf
		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">perm_identity</i>
		                        </span>
		                        <div class="form-line">
		                            <input id="npm" type="text" class="form-control{{ $errors->has('npm') ? ' is-invalid' : '' }}" name="npm" value="{{ old('npm') }}" placeholder="NPM/ID" required autofocus>
		                            @if ($errors->has('npm'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('npm') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>

		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">dashboard</i>
		                        </span>
		                        <div class="form-line">
		                            <select class="form-control" id="sel1" class="form-control" name="id_prodi">
		                                <option value="">##Select Program Studi##</option>
		                                @foreach($prodis as $prodi)
		                                    <option value="{{$prodi['id']}}">{{$prodi['nama_prodi']}}</option>
		                                @endforeach
		                            </select>

		                            @if ($errors->has('id_prodi'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('id_prodi') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>

		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">person</i>
		                        </span>
		                        <div class="form-line">
		                            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" placeholder="Name" required>

		                            @if ($errors->has('name'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('name') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>

		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">image</i>
		                        </span>
		                        <div class="form-line">
		                            <input id="foto" type="file" class="form-control{{ $errors->has('foto') ? ' is-invalid' : '' }}" name="foto" value="{{ old('foto') }}" required>

		                            @if ($errors->has('foto'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('foto') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>



		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">email</i>
		                        </span>
		                        <div class="form-line">
		                            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" placeholder="Email" required>

		                            @if ($errors->has('email'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('email') }}</strong>
		                                </span>
		                            @endif                            
		                        </div>
		                    </div>

		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">account_circle</i>
		                        </span>
		                        <div class="form-line">
		                            <select class="form-control" id="sex" class="form-control" name="sex">
		                                <option value="">##Select Gender##</option>
		                                <option value="male">Male</option>
		                                <option value="female">Female</option>
		                            </select>
		                            @if ($errors->has('sex'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('sex') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>


		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">dashboard</i>
		                        </span>
		                        <div class="form-line">
		                            <select class="form-control" id="sel1" class="form-control" name="role">
		                                <option value="user">##Select Role##</option>
	                                    <option value="user">User</option>
	                                    <option value="admin">Admin</option>
		                            </select>

		                            @if ($errors->has('role'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('role') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>

		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">lock</i>
		                        </span>
		                        <div class="form-line">
		                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" placeholder="Password" required>
		                                @if ($errors->has('password'))
		                                    <span class="invalid-feedback">
		                                        <strong>{{ $errors->first('password') }}</strong>
		                                    </span>
		                                @endif
		                        </div>
		                    </div>

		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">lock</i>
		                        </span>
		                        <div class="form-line">
		                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required placeholder="Confirmation Password">
		                        </div>
		                    </div>

		                    <button class="btn btn-lg btn-primary waves-effect" type="submit">{{ __('Create') }}</button>
		                </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header bg-green">
                        <h2>
                            User<small>Create Data User</small>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">

		                <form method="POST" action="{{action('UserController@update', $id)}}" enctype="multipart/form-data">
		                    @csrf
                            <input name="_method" type="hidden" value="PATCH">                    	
		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">perm_identity</i>
		                        </span>
		                        <div class="form-line">
		                            <input id="npm" type="text" class="form-control{{ $errors->has('npm') ? ' is-invalid' : '' }}" name="npm" value="{{ $user->npm }}" placeholder="NPM/ID" required autofocus>
		                            @if ($errors->has('npm'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('npm') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>

		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">dashboard</i>
		                        </span>
		                        <div class="form-line">
		                            <select class="form-control" id="sel1" class="form-control" name="id_prodi">
		                                @foreach($prodis as $prodi)
		                                	<option value="{{ $prodi['id'] }}" {{ $prodi['id'] == $user->id_prodi ? 'selected':'' }} >{{$prodi['nama_prodi']}}</option>
		                                @endforeach
		                            </select>

		                            @if ($errors->has('id_prodi'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('id_prodi') }}</strong>
		                                </span>
		                            @endif		                            
		                        </div>
		                    </div>

		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">person</i>
		                        </span>
		                        <div class="form-line">
		                            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $user->name }}" placeholder="Name" required>

		                            @if ($errors->has('name'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('name') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>

		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">image</i>
		                        </span>
		                        <div class="form-line">
		                        	<div class="image">
			                        	<img src="{{asset('storage/uploads/'.$user->foto)}}" width="100px" height="100px" style="object-fit: cover;">
			                        </div>	
		                            <input id="foto" type="file" class="form-control{{ $errors->has('foto') ? ' is-invalid' : '' }}" name="foto" value="{{ $user->foto }}">

		                            @if ($errors->has('foto'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('foto') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>



		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">email</i>
		                        </span>
		                        <div class="form-line">
		                            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ $user->email }}" placeholder="Email" required>

		                            @if ($errors->has('email'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('email') }}</strong>
		                                </span>
		                            @endif                            
		                        </div>
		                    </div>

		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">account_circle</i>
		                        </span>
		                        <div class="form-line">
		                            <select class="form-control" id="sex" class="form-control" name="sex">
										<option value="male" {{ $user->sex=='male' ? 'selected':'' }} >Male</option>
										<option value="femal" {{ $user->sex=='female' ? 'selected':'' }} >Female</option>
		                            </select>
		                            @if ($errors->has('sex'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('sex') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>


		                    <div class="input-group">
		                        <span class="input-group-addon">
		                            <i class="material-icons">dashboard</i>
		                        </span>
		                        <div class="form-line">
		                            <select class="form-control" id="sel1" class="form-control" name="role">
										<option value="user" {{ $user->role=='user' ? 'selected':'' }} >User</option>
										<option value="admin" {{ $user->role=='admin' ? 'selected':'' }} >Admin</option>
									</select>

		                            @if ($errors->has('role'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('role') }}</strong>
		                                </span>
		                            @endif
		                        </div>
		                    </div>

		                    <button class="btn btn-lg btn-primary waves-effect" type="submit">{{ __('Update') }}</button>
		                </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                @if (\Session::has('success'))
                  <div class="alert alert-success">
                    <p>{{ \Session::get('success') }}</p>
                  </div><br />
                 @endif                    
                    <div class="header bg-green">
                        <h2>
                            User<small>Data User</small>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li>
                                <a href="{{action('UserController@create')}}">
                                    <i class="material-icons">add</i>
                                </a>
                            </li>
                          
                            <li>                                
                                <a href="javascript:void(0);" class="js-search" data-close="true">
                                    <i class="material-icons">search</i>
                                </a>                                
                            </li>
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">


                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>NPM/ID</th>
                                        <th>Nama </th>
                                        <th>Email</th>                                            
                                        <th>Hak Akses</th>
                                        <th colspan="2">Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>NPM/ID</th>
                                        <th>Nama </th>
                                        <th>Email</th>    
                                        <th>Hak Akses</th>
                                        <th colspan="2">Action</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <tr>
                                        @foreach($users as $user)
                                        <tr>
                                            <td>{{$user['npm']}}</td>
                                            <td>{{$user['name']}}</td>
                                            <td>{{$user['email']}}</td>
                                            <td>{{$user['role']}}</td>
                                            
                                            <td class="js-sweetalert">
                                                <a href="{{action('UserController@edit', $user['npm'])}}" >
                                                    <button type="button" class="btn bg-green waves-effect btn-xs">
                                                        <i class="material-icons">edit</i>
                                                    </button>
                                                </a>

                                                <form action="{{action('UserController@destroy', $user['npm'])}}" method="post"  accept-charset="UTF-8" style="display:inline">
                                                    @csrf
                                                    <input name="_method" type="hidden" value="DELETE">
                                                    <button type="submit" class="btn bg-red waves-effect btn-xs" data-type="cancel" onclick="return confirm('Hapus ?')">
                                                        <i class="material-icons">delete</i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection