routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', function () {
    return view('indeks');
});


Route::get('/mutabaah/pdf', 'MutabaahController@pdf')->middleware('auth');
Route::get('/mutabaah/grafik', 'MutabaahController@grafik')->middleware('auth');
Route::resource('mutabaah', 'MutabaahController')->middleware('auth');
Route::get('mutabaah/download/{type}', 'MutabaahController@download')->middleware('isadmin');

Route::resource('prodi', 'ProdiController')->middleware('isadmin');
Route::get('admin', 'DashboardAdminController@dashboard')->middleware('isadmin');
Route::resource('user', 'UserController')->middleware('isadmin');

app/Prodi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Prodi extends Model
{
    //
}

app/Http/Controllers/ProdiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Prodi;

class ProdiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //query prodi
        $prodis = Prodi::when($request->keyword, function ($query) use ($request) {
            $query->where('id', 'like', "%{$request->keyword}%");
        })->latest()->paginate(5);

        $prodis->appends($request->only('keyword'));

        return view('admin.prodis.index',compact('prodis'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.prodis.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $prodi = new Prodi();
        $prodi->id = $request->get('id');
        $prodi->nama_prodi = $request->get('nama_prodi');
        $prodi->tahun_berdiri = $request->get('tahun_berdiri');
        $prodi->akreditasi = $request->get('akreditasi');                
        $prodi->save();
        return redirect('prodi')->with('success','Berhasil Tambah Data');        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $prodi = Prodi::find($id);
        return view('admin.prodis.edit',compact('prodi','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $prodi = Prodi::find($id);
        $prodi->id = $request->get('id');
        $prodi->nama_prodi = $request->get('nama_prodi');
        $prodi->tahun_berdiri = $request->get('tahun_berdiri');
        $prodi->akreditasi = $request->get('akreditasi');                
        $prodi->save();
        return redirect('prodi')->with('success','Berhasil Tambah Data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $prodi = Prodi::find($id);
        $prodi->delete();
        return redirect('prodi')->with('success','Employee Has Been Deleted');          
    }
}

resources/views/admin/prodis/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header bg-green">
                        <h2>
                            {{ __('Program Studi') }}
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <form method="POST" action="{{ route('prodi.store') }}">
                            @csrf
                            <div class="row clearfix">
                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                    <label for="id">{{ __('ID Program Studi') }}</label>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="id" class="form-control" placeholder="Kode Progam Studi" name="id">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row clearfix">
                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                    <label for="nama_prodi">{{ __('Nama Program Studi') }}</label>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="nama_prodi" class="form-control" placeholder="Nama Program Studi" name="nama_prodi">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row clearfix">
                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                    <label for="tahun_berdiri">{{ __('Tahun Berdiri') }}</label>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="tahun_berdiri" class="form-control" placeholder="Tahun Berdiri" name="tahun_berdiri">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row clearfix">
                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                    <label for="akreditasi">{{ __('Akreditasi') }}</label>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <select class="form-control show-tick" id="akreditasi" name="akreditasi">
                                                <option value="-">--Pilih Akreditasi--</option>
                                                <option value="A">A</option>
                                                <option value="B">B</option>
                                                <option value="C">C</option>
                                                <option value="-">-</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row clearfix">
                                <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                    <button type="submit" class="btn btn-primary m-t-15 waves-effect">Create</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/prodis/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header bg-green">
                        <h2>
                            {{ __('Program Studi') }}
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <form method="POST" action="{{action('ProdiController@update', $id)}}">
                            @csrf
                            <input name="_method" type="hidden" value="PATCH">
                            <div class="row clearfix">
                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                    <label for="id">{{ __('ID Program Studi') }}</label>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="id" class="form-control" placeholder="Kode Progam Studi" name="id" value="{{$prodi->id}}">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row clearfix">
                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                    <label for="nama_prodi">{{ __('Nama Program Studi') }}</label>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="nama_prodi" class="form-control" placeholder="Nama Program Studi" name="nama_prodi" value="{{$prodi->nama_prodi}}">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row clearfix">
                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                    <label for="tahun_berdiri">{{ __('Tahun Berdiri') }}</label>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="tahun_berdiri" class="form-control" placeholder="Tahun Berdiri" name="tahun_berdiri" value="{{$prodi->tahun_berdiri}}">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row clearfix">
                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                    <label for="akreditasi">{{ __('Akreditasi') }}</label>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <select class="form-control show-tick" id="akreditasi" name="akreditasi">
                                                <option value="A" {{ ( $prodi->akreditasi == 'A' ) ? 'selected' : '' }}>A</option>
                                                <option value="B" {{ ( $prodi->akreditasi == 'B' ) ? 'selected' : '' }}>B</option>
                                                <option value="C" {{ ( $prodi->akreditasi == 'C' ) ? 'selected' : '' }}>C</option>
                                                <option value="-" {{ ( $prodi->akreditasi == '-' ) ? 'selected' : '' }}>-</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row clearfix">
                                <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Kirim') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/prodis/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                @if (\Session::has('success'))
                  <div class="alert alert-success">
                    <p>{{ \Session::get('success') }}</p>
                  </div><br />
                 @endif                    
                    <div class="header bg-green">
                        <h2>
                            Program Studi<small>Data Program Studi</small>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li>
                                <a href="{{action('ProdiController@create')}}">
                                    <i class="material-icons">add</i>
                                </a>
                            </li>
                          
                            <li>                                
                                <a href="javascript:void(0);" class="js-search" data-close="true">
                                    <i class="material-icons">search</i>
                                </a>                                
                            </li>
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">


                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>Id Program Studi</th>
                                        <th>Nama Program Studi</th>
                                        <th>Tahun Berdiri</th>
                                        <th>Akreditasi</th>    
                                        <th colspan="2">Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Id Program Studi</th>
                                        <th>Nama Program Studi</th>
                                        <th>Tahun Berdiri</th>
                                        <th>Akreditasi</th>    
                                        <th colspan="2">Action</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <tr>
                                        @foreach($prodis as $prodi)
                                        <tr>
                                            <td>{{$prodi['id']}}</td>
                                            <td>{{$prodi['nama_prodi']}}</td>
                                            <td>{{$prodi['tahun_berdiri']}}</td>
                                            <td>{{$prodi['akreditasi']}}</td>
                                            <td class="js-sweetalert">
                                                <a href="{{action('ProdiController@edit', $prodi['id'])}}" >
                                                    <button type="button" class="btn bg-green waves-effect btn-xs">
                                                        <i class="material-icons">edit</i>
                                                    </button>
                                                </a>

                                                <form action="{{action('ProdiController@destroy', $prodi['id'])}}" method="post"  accept-charset="UTF-8" style="display:inline">
                                                    @csrf
                                                    <input name="_method" type="hidden" value="DELETE">
                                                    <button type="submit" class="btn bg-red waves-effect btn-xs" data-type="cancel" onclick="return confirm('Hapus ?')">
                                                        <i class="material-icons">delete</i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tr>
                                </tbody>
                            </table>
                            {!! $prodis->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection